SelectTarget(1)
character_1:UseSkill(2)
SelectTarget(2)
character_1:UseSkill(4)
SelectTarget(3)
character_2:UseSkill(2)
--character_2:UseSkill(2)
--    :UseSkill(1)
--character_1:UseSkill(2)
--character_3:UseSkill(1)
--character_4:UseSkill(2)

Attack()
Wait(2400)
--TerminateBattle()
--Refresh()